
version: '3.9'
name: citadel
services:
  citadeldb:
    container_name: citadeldb
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=citadel
    ports:
      - '5433:5432'
    volumes: 
      - citadeldb:/var/lib/postgresql/data
volumes:
  citadeldb:
    driver: local